services:
  backend:
    build: ./backend
    ports:
      - "8417:8417"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend:/app
      - huggingface_cache:/root/.cache/huggingface

  frontend:
    build: ./frontend
    ports:
      - "5417:5417"
    depends_on:
      - backend

volumes:
  huggingface_cache:
